/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define HAVE_GSTACK 0

#define HAVE_LIBSYSTEMD 1

#define HAVE_LIBWACOM 1

#define HAVE_LIBWACOM_GET_BUTTON_EVDEV_CODE 1

#define HAVE_LIBWACOM_GET_PAIRED_DEVICE 1

#define HAVE_LOCALE_H 1

#define HAVE_VERSIONSORT 1

#define HTTP_DOC_LINK "https://wayland.freedesktop.org/libinput/doc/latest/"

#define LIBINPUT_QUIRKS_DIR "/usr/share/libinput"

#define LIBINPUT_QUIRKS_FILES "quirks/10-generic-keyboard.quirks:quirks/10-generic-lid.quirks:quirks/10-generic-trackball.quirks:quirks/30-vendor-aiptek.quirks:quirks/30-vendor-alps.quirks:quirks/30-vendor-contour.quirks:quirks/30-vendor-cypress.quirks:quirks/30-vendor-elantech.quirks:quirks/30-vendor-ibm.quirks:quirks/30-vendor-kensington.quirks:quirks/30-vendor-logitech.quirks:quirks/30-vendor-madcatz.quirks:quirks/30-vendor-microsoft.quirks:quirks/30-vendor-razer.quirks:quirks/30-vendor-synaptics.quirks:quirks/30-vendor-trust.quirks:quirks/30-vendor-vmware.quirks:quirks/30-vendor-wacom.quirks:quirks/50-system-acer.quirks:quirks/50-system-apple.quirks:quirks/50-system-asus.quirks:quirks/50-system-chicony.quirks:quirks/50-system-cyborg.quirks:quirks/50-system-dell.quirks:quirks/50-system-google.quirks:quirks/50-system-hp.quirks:quirks/50-system-lenovo.quirks:quirks/50-system-system76.quirks:quirks/50-system-toshiba.quirks"

#define LIBINPUT_QUIRKS_OVERRIDE_FILE "/etc/libinput/local-overrides.quirks"

#define LIBINPUT_QUIRKS_SRCDIR "/home/xuser/libinput/quirks"

#define LIBINPUT_TOOL_PATH "/usr/libexec/libinput"

#define MESON_BUILD_ROOT "/home/xuser/libinput/builddir"

#define _GNU_SOURCE 1

