/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define LIBINPUT_DEVICE_GROUPS_RULES_FILE "/home/xuser/libinput/builddir/80-libinput-device-groups-litest.rules"

#define LIBINPUT_FUZZ_OVERRIDE_UDEV_RULES_FILE "/home/xuser/libinput/builddir/90-libinput-fuzz-override-litest.rules"

